export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCT_BY_NAME";

export const GET_ALL_RECEIPTS = "GET_ALL_RECEIPTS";
export const GET_RECEIPT_BY_ID = "GET_RECEIPT_BY_ID";
export const GET_RECEIPTS_BY_DATE = "GET_RECEIPTS_BY_DATE";
export const GET_SLICED_RECEIPTS = "GET_SLICED_RECEIPTS";

export const GET_ALL_CASHIERS = "GET_ALL_CASHIERS";
export const GET_CASHIER_BY_ID = "GET_CASHIER_BY_ID";

export const GET_ALL_REGISTERS = "GET_ALL_REGISTERS";
export const GET_REGISTER_BY_ID = "GET_REGISTER_BY_ID";
